version: '3'

services:
  uvgcloudbackend:
    #container_name: uvgcloudbackend
    #image: backendcontainer:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./uvgcloudbackend:/project
